
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --colour=auto'
alias via='vi ~/.apparixrc'
alias c='clear'

# source $HOME/.bash_path
# source $HOME/.bash_apparix
# source $HOME/.bash_generic


export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

bind '"\t":menu-complete'

## bind '^F:reverse-search-history'
## bind '^G:forward-search-history'


function generic_powerprompt()
{   PS1="($USER|$(hostname | cut -d. -f1)|$(echo $PWD | sed 's/^.*\/\([^\/]*\/[^\/]*$\)/\1/')) "
    # or, if you get it to work
}
generic_powerprompt
function cd
{  if test "x$*" != x; then
      command cd "$*"      # check syntax of this
    else
      command cd
   fi
   generic_powerprompt
}

export INPUTRC=~/.inputrc

source $HOME/.bash_apparix

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
   alias dir='dir --color=auto'
   alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
